### PR TITLE
Better way to create symbolic link and removed unnecessary variable

### PR DESCRIPTION
**Pull request by FWest98**
Using system dll's instead of the commandline

### CODE REVIEW

**Comment by FWest98** [comment]
Maybe reconsider using Junction Points at all, as they only work on NTFS filesystems. In the future more users may use exFAT or ReFS...

**Comment by Krutonium** [comment]
I don't think users will be going to exFat, since NTFS is still better than that, but I appreciate your thinking ahead. Quickly reviewed the code, Merging.

**Comment by Krutonium** [comment]
I forgot to ask if this code was done.

**Comment by FWest98** [comment]
Yes, it is done ;)

-------- Oorspronkelijk bericht --------
Van: Krutonium notifications@github.com 
Datum: 2015-02-13  18:49  (GMT+01:00) 
Aan: PFCKrutonium/OpenRCT2Launcher OpenRCT2Launcher@noreply.github.com 
Cc: Floris Westerman floriswesterman@msn.com 
Onderwerp: Re: [OpenRCT2Launcher] Better way to create symbolic link and removed unnecessary variable (#15) 

I forgot to ask if this code was done.

**Comment by Krutonium** [comment]
Okay, Merged and Added your name to the Credits :)

**Pull request merged**
