### PR TITLE
Fixed some bugs

### PR DESCRIPTION
**Pull request by falki147**
Most bugs should be fixed now however I couldn't reproduce the one from
the forums (https://openrct.net/forum/topic/46/error-when-launching)

### CODE REVIEW

**Comment by FWest98** [comment]
Why did you change the ReparsePointLib Save function to sync instead of async?

**Comment by falki147** [comment]
If I would use async the launcher would just start the exe while the launcher still writes to the INI File
-> OpenRCT2 prints "ERROR[..\src\config.c358 <config_save>} Unable to write to the config file."

I thought the simplest solution would be to just change it back to sync since no one else uses it anyways and I would probably forget again to make sure it doesn't get called asynchronous which results in bugs like this. What's the point of this anyways? Where do we need it? I'm sorry if I broke something but it didn't make any sense to me.

**Comment by FWest98** [comment]
If that happens, you invoke the async function wrongly or the order of execution is wrong. That you can just use the synchronous function without changing the calling code indicates that you didn't `await` the call, so no shit it didn't wait.
Normal synchronous functions for reading from storage lock up the entire thread. Async functions don't do that, until the `await` keyword.
So:

```
var result = await SomeAsyncFunction(); // this locks the thread just like synchronous actions do

var execution = SomeAsyncFunction();
/* Much more thing to do */
var result = await execution; // now, the things in between are done in the time that SomeAsyncFunction is waiting for storage or something
```

And, even while using await directly, while waiting, other threads (or other functions in the same thread) can run as well. So, if you end up accessing storage from the UI-thread (the worst you can do), the UI doesn't lock up while waiting for the storage.

Why not use it by the way? All new functions are async, all new frameworks are. You have to get used to it anyway, and by creating as much async as possible this project is more prepared to future changes in the API.

**Comment by falki147** [comment]
Oh I'm sorry. I just thought async functions are the same as normal threads (in some strange way, I should have known since it returns a task). I don't use .net languages often so I don't know things like this ;)

Yes, I wasn't using await since I would have had to switch the whole function itself to async (the compiler threw an error if I recall correctly) and I thought to prevent future errors it's better to change it back right away. I guess I should change the save function to async and the ReparsePointLib save function to async too?

**Comment by FWest98** [comment]
If one function is async, the entire calling stack should be as well. I think it's best to change everything.
So void returns Task, **except** event callbacks (or whatever they are called), they need to return void.

**Pull request merged**
